### ISSUE TITLE
Отслеживать все клики, а не только клики по линкам и кнопкам

### ISSUE THREAD

**Issue by foolosopher** [rockstat/web-sdk#2]
**Ситуация:** Заметил, что не все нажатия на кнопки в интерфейсе попадают в трекинг. Авторитетные коллеги пояснили, что бывают кнопки, которые по коду кнопками не являются. просто выглядят так.

Тогда нужно или их все переделать под кнопки, или прокинуть отдельные события - оба варианта не очень удобны и не защищают от похожих ситуаций в будущем.

**Предложение:**  Записывать по умолчанию не только все клики по кнопкам, а вообще все клики. Альтернативный вариант - дать возможность такой настройки в конфиге

Не перегрузит ли это клиента? хватит ли сети?

**Comment by madiedinro** [comment]
@foolosopher готово ведь? закрывай тогда)

**Comment by foolosopher** [comment]
спасибо! все на месте
