### ISSUE TITLE
WebSDK не определяет наличие яндекс метрики 

### ISSUE THREAD

**Issue by BelkinVadim** [rockstat/web-sdk#3]
Перестал отправляться в статистику идентификатор яндекс метрики. Посмотрел код и обнаружил что WebSDK не может определить наличие метрики. В коде идет проверка `win.Ya && win.Ya.Metrika`, но из-за того что у нас вторая версия метрики, которая определяется `win.Ya.Metrika2`, WebSDK не находит ее.

**Comment by madiedinro** [comment]
Уф, кажется уже исправлено все.
